### ISSUE TITLE
motif instances

### ISSUE THREAD

**Issue by igordot** [rajanil/msCentipede#2]
This is not really an issue (maybe a documentation issue). The tool takes two inputs. One is a BAM file, which makes sense. The other is a file of motif instances. Do you have any suggestions on where to get or how to generate that file?

**Comment by rajanil** [comment]
Given a position weight matrix for a transcription factor, the list of motif instances is typically generated by scanning the genome for sequences that have a higher likelihood under the PWM model than a background model. Since the format for PWM matrices tend to vary and users might want to only include a subset of all motif instances, we decided to let this be an input generated by the user separately. Thanks for the suggestion; I will update the documentation with this description.

**Comment by igordot** [comment]
I know there is at least one database (http://compbio.mit.edu/encode-motifs/), but it's human only. Any additional resources or tools would be very helpful.

**Comment by igordot** [comment]
Sorry. Do you have any updates on this topic?

**Comment by rajanil** [comment]
The encode database is quite useful. Another database of PWM models for human and mouse factors is from this paper. http://www.sciencedirect.com/science/article/pii/S0092867412014961

Two other commonly used databases of PWM models are TRANSFAC (http://www.gene-regulation.com/pub/databases.html) and JASPAR (http://jaspardev.genereg.net/), which have models for factors in other eukaryotes.

Hope this helps!
